apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-service
  namespace: aieducator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-service
  template:
    metadata:
      labels:
        app: ai-service
    spec:
      containers:
        - name: ai-service
          image: bojanabojchovska/ai-service:latest
          ports:
            - containerPort: 8000
          env:
            - name: HUGGINGFACEHUB_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: HUGGINGFACEHUB_API_TOKEN
            - name: PINECONE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: PINECONE_API_KEY
            - name: PINECONE_ENV
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: PINECONE_ENV
            - name: PINECONE_INDEX_NAME
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: PINECONE_INDEX_NAME
            - name: PYTHONUNBUFFERED
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: PYTHONUNBUFFERED
